#!/usr/bin/env python3
"""Compose the attested bouncy_01 browser take with short feature scenes.

The only dynamic portion is a 22-second browser capture that has been checked
against ``demo_bouncy_01_v1``. The final 38 seconds are 19 distinct,
two-second feature scenes: key, L1/L2, compact reward, ball customization,
power-gauge states, and other game mechanisms. This prevents a direct-clear
first-stage recording or a long static clear popup from being silently reused.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import shutil
import sys
from pathlib import Path
from typing import Any

from verify_demo_pipeline import ROOT, DEFAULT_MANIFEST, ValidationError, validate_manifest


def _load_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise ValidationError(f"browser-capture attestation is missing: {path}") from error
    except json.JSONDecodeError as error:
        raise ValidationError(f"invalid browser-capture attestation: {error}") from error


def _validate_attestation(attestation_path: Path, contract: dict[str, Any]) -> None:
    attestation = _load_json(attestation_path)
    expected = {
        "demoPlanId": contract["demoPlanId"],
        "stageId": contract["stageId"],
        "patternId": contract["patternId"],
        "fixtureId": contract["fixtureId"],
        "expectedEvents": contract["expectedEvents"],
        "directClear": False,
        "aim": contract["aim"],
    }
    for key, value in expected.items():
        if attestation.get(key) != value:
            raise ValidationError(
                f"browser capture attestation {key}={attestation.get(key)!r}; expected {value!r}"
            )
    if not isinstance(attestation.get("capturedAtUtc"), str):
        raise ValidationError("browser capture attestation must record capturedAtUtc")
    if not isinstance(attestation.get("sourceUrl"), str) or not attestation["sourceUrl"]:
        raise ValidationError("browser capture attestation must record sourceUrl")
    evidence = attestation.get("telemetryEvidence")
    if not isinstance(evidence, dict):
        raise ValidationError("browser capture lacks verified telemetry evidence")
    if (
        evidence.get("eventCount", 0) <= 0
        or evidence.get("directClear") is not False
        or not isinstance(evidence.get("sessionId"), str)
        or not isinstance(evidence.get("captureStartedAtUtc"), str)
    ):
        raise ValidationError("browser telemetry does not prove a non-direct successful take")
    if abs(float(evidence.get("power", -1)) - contract["aim"]["power"]) > 0.001:
        raise ValidationError("browser telemetry power does not match the fixture")
    if abs(float(evidence.get("angleRadians", 99)) - math.radians(contract["aim"]["degrees"])) > math.radians(0.25):
        raise ValidationError("browser telemetry angle does not match the fixture")
    if int(evidence.get("wallUseCount", 0)) < contract["expectedEvents"].count("bounced"):
        raise ValidationError("browser telemetry does not prove three wall bounces")
    tail_seconds = evidence.get("captureTailSeconds")
    if not isinstance(tail_seconds, (int, float)) or not 1.5 <= tail_seconds <= 2.0:
        raise ValidationError("browser telemetry does not prove the required 1.5–2.0 second ending slack")
    gimmicks = set(evidence.get("gimmickTypes", []))
    if not {"bouncy", "wall_reflection"}.issubset(gimmicks):
        raise ValidationError("browser telemetry lacks the required bouncy reflection route")


def _source_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _validate_scene_evidence(evidence_path: Path, manifest: dict[str, Any]) -> None:
    """Reject a montage when a Golden source changed after its targeted test pass."""
    evidence = _load_json(evidence_path)
    if evidence.get("schemaVersion") != 1:
        raise ValidationError("feature-scene evidence has an unsupported schema version")
    suites = manifest["sourceVerification"]["requiredSuites"]
    if evidence.get("suites") != suites:
        raise ValidationError("feature-scene evidence was not generated by the required Golden suites")
    hashes = evidence.get("sourceSha256")
    if not isinstance(hashes, dict):
        raise ValidationError("feature-scene evidence lacks source hashes")
    for scene in manifest["featureScenes"]:
        source_name = scene["source"]
        source = ROOT / source_name
        if hashes.get(source_name) != _source_hash(source):
            raise ValidationError(
                f"feature scene {scene['id']!r} differs from the Golden source attested by the test run"
            )


def _copy(source: Path, output_dir: Path, index: int) -> int:
    shutil.copy2(source, output_dir / f"frame-{index:05d}.png")
    return index + 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument(
        "--base-frames-dir",
        type=Path,
        default=Path("recordings/.recording-frames"),
    )
    parser.add_argument(
        "--output-frames-dir",
        type=Path,
        default=Path("recordings/.demo-frames"),
    )
    parser.add_argument(
        "--attestation",
        type=Path,
        default=None,
        help="JSON emitted by record_gameplay_frames.py after a verified bouncy take",
    )
    parser.add_argument(
        "--scene-evidence",
        type=Path,
        default=None,
        help="JSON emitted by verify_demo_scene_sources.py after targeted Golden tests",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate the manifest and print the planned output without reading capture frames",
    )
    args = parser.parse_args()
    manifest_path = args.manifest.resolve()

    try:
        validate_manifest(manifest_path)
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        video = manifest["video"]
        browser_capture = manifest["browserCapture"]
        scenes = manifest["featureScenes"]
        expected_base_count = video["fps"] * browser_capture["durationSeconds"]
        feature_count = sum(video["fps"] * scene["seconds"] for scene in scenes)
        expected_total = video["fps"] * video["durationSeconds"]
        if expected_base_count + feature_count != expected_total:
            raise ValidationError("manifest frame total is not exactly 60 seconds")
    except ValidationError as error:
        print(f"DEMO COMPOSE INVALID: {error}", file=sys.stderr)
        return 1

    print(
        f"planned composition: {expected_base_count} verified browser frames + "
        f"{feature_count} feature frames = {expected_total} frames "
        f"({video['durationSeconds']:.1f}s at {video['fps']}fps)"
    )
    if args.dry_run:
        for scene in scenes:
            print(f"- {scene['id']}: {scene['seconds']}s · {scene['source']}")
        return 0

    attestation_path = args.attestation or args.base_frames_dir / "demo-attestation.json"
    scene_evidence_path = args.scene_evidence or args.base_frames_dir / "demo-scene-evidence.json"
    try:
        _validate_attestation(attestation_path, manifest["contract"])
        _validate_scene_evidence(scene_evidence_path, manifest)
    except ValidationError as error:
        print(f"DEMO COMPOSE INVALID: {error}", file=sys.stderr)
        return 1

    base_frames = sorted(args.base_frames_dir.glob("frame-*.png"))
    if len(base_frames) != expected_base_count:
        print(
            f"DEMO COMPOSE INVALID: expected exactly {expected_base_count} browser frames "
            f"({browser_capture['durationSeconds']}s), found {len(base_frames)}",
            file=sys.stderr,
        )
        return 1

    args.output_frames_dir.mkdir(parents=True, exist_ok=True)
    for old in args.output_frames_dir.glob("frame-*.png"):
        old.unlink()

    frame_index = 0
    for source in base_frames:
        frame_index = _copy(source, args.output_frames_dir, frame_index)
    for scene in scenes:
        source = ROOT / scene["source"]
        for _ in range(video["fps"] * scene["seconds"]):
            frame_index = _copy(source, args.output_frames_dir, frame_index)

    provenance = {
        "manifest": str(manifest_path),
        "attestation": str(attestation_path.resolve()),
        "sceneEvidence": str(scene_evidence_path.resolve()),
        "frameCount": frame_index,
        "durationSeconds": frame_index / video["fps"],
        "orientation": video["orientation"],
    }
    (args.output_frames_dir / "demo-provenance.json").write_text(
        json.dumps(provenance, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(
        f"demo frames composed: {frame_index} · {frame_index / video['fps']:.1f}s · "
        f"{len(scenes)} feature scenes × 1–2s"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
